spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: lenamargariann
    password: 41734744
    url: jdbc:postgresql://localhost:5432/mindbody_prod_db
  application:
    name: GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMTAxMDA1OSwiaWF0IjoxNzAxMDEwMDU5fQ.CP7wFAXamZmq21-S8_fHYMOhU4zQ7fuPhQ5nboYHaZE
  expiration: 120000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        preferIpAddress: true
server:
  port: 9091